<a href="https://colab.research.google.com/github/chinmaesalvacion/LinearAlgebra2021/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Linear Algebra for ECE
## Laboratory 4 :Matrices

Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

## Objectives
At the end of this activity you will be able to:


1.   Be familiar with matrices and their relation to linear equations.
2.   Perform basic matrix operations.

1.   Program and translate matrix equations and operations using Python.






# Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

NumPy is a Python library allowing easy numerical calculations involving single and multidimensional arrays and matrices. [1]

## Matrices
Matrix is a special case of two dimensional array where each data element is of strictly same size. It is a two dimensional array but not vice versa.They are  considered to be very important data structures for many mathematical and scientific calculations. [2]

Let's say for example you have $A$ and $B$ as system of equation. 

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

We could see that $A$ is a system of 2 equations with 2 parameters. While $B$ is a system of 3 equations with 3 parameters. We can represent as matrices as:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

So assuming that you laready discussed the fundamental representations of matrices, their types and operations,  We'll proceed in doing them in here in Python.

## Declaring Matrices

A Python matrix is a specialized two-dimensional rectangular array of data stored in rows and columns. The data in a matrix can be numbers, strings, expressions, symbols, etc. Matrix is one of the important data structures that can be used in mathematical and scientific calculations. [3] 

![image](https://cdn.guru99.com/images/2/062620_0641_PythonMatri1.png)

As seen in the picture above, it illustrates the parts of the matrix. But keep in mind that Python does not have a straightforward way to implement a matrix data type. The python matrix makes use of arrays, and the same can be implemented. It will be further on discussed in the following parts of the lab activity.

In [ ]:
## Since we'll keep on describing matrices. Let's make a function
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Declaring a 2 x 2 matrix
A = np.array([
      [1,2],
      [3,1]    
])
describe_mat(A)


Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [ ]:
## Declaring a 3 x 2 matrix
B = np.array([
      [8,2],
      [3,1],
      [1,1]    
])
describe_mat(B)

Matrix:
[[8 2]
 [3 1]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



## Categorizing Matrices

In this laboratory activity, matrices are categorized through their <b>shape</b> and <b>element values</b>. 

# According to shape

# Row and Column Matrices

Row and column matrices are common in vector and matrix computations. They can also represent row and column spaces of a bigger vector space. Row and column matrices are represented by a single column or single row. So with that being, the shape of row matrices would be $1 \times j$ and column matrices would be $i \times 1$.

In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
      1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
      [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
         [1],
         [2],
         [5]           
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



## Square Matrices

Square matrices that have the same row and column sizes. We could say a matrix is square if $i = j$. We can tweak our matrix descriptor function to determine square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



## According to element values

## Null Matrix

A Null Matrix is matrix that has no elements. It is always a subspace if any vector or matrix.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


## Zero Matrix

A zero matrix can be any rectangular matrix but with all elements having a value of 0.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


## Ones Matrix

A ones matrix, just like the zero matrix, can be any rectangular matrix but all of its elements are 1s instead of 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


## Diagonal Matrix

A diagonal matrix is a square matrix that has values only at the diagonal of the matrix. 

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])
# a[1,1], a[2,2], a[3,3], ... a[n-1,n-1]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,3,5,7])
np.diag(d).shape == d.shape[0] == d.shape[1]

## Identity Matrix

An identity matrix is a special diagonal matrix in which the values at the diagonal are ones.

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Upper Triangular Matrix

An upper triangular matrix is a matrix that has no values below the diagonal. 

In [ ]:
np.array([
    [1,2,3],
    [0,3,1],
    [0,0,5]
])

array([[1, 2, 3],
       [0, 3, 1],
       [0, 0, 5]])

# Lower Triangular Matrix

A lower triangular matrix is a matrix that has no values above the diagonal.

In [ ]:
np.array([
    [1,0,0],
    [5,3,0],
    [7,8,5]
])

array([[1, 0, 0],
       [5, 3, 0],
       [7, 8, 5]])

## Matrix Algebra

## Addition

In [ ]:
A = np.array ([
      [1,2],
      [2,3],
      [4,1]      
])
B = np.array ([
      [2,2],
      [0,0],
      [1,1]      
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [ ]:
##2+A ##Broadcasting
2*np.ones(A.shape)+A

array([[3., 4.],
       [4., 5.],
       [6., 3.]])

In [ ]:
2+A == 2*np.ones(A.shape)+A

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Subtraction

In [ ]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [ ]:
3-B ## == 3*np.ones(B.shape)-B

array([[1, 1],
       [3, 3],
       [2, 2]])

##Element-wise Multiplication

In [ ]:
A*B

array([[2, 4],
       [0, 0],
       [4, 1]])

In [ ]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

ALPHA = to avoid having inf in the matrix. it adds a little value to get an exact number rather than infinity.

In [ ]:
A/B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.5, 1. ],
       [inf, inf],
       [4. , 1. ]])

In [ ]:
alpha=10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [ ]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

# Activity

# Task 1


Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
## Function area
def mat_desc(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
## Matrix declarations

A = np.array([
    [1,6,3],
    [3,2,7],
    [4,1,9],          
])

In [ ]:
## Test Areas
print(f'Example Matrix: \n')
mat_desc(A)

Example Matrix: 

Matrix:
[[1 6 3]
 [3 2 7]
 [4 1 9]]

Shape:	(3, 3)
Rank:	2



In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

non_square_mat = np.array([
    [1,7,8],
    [3,0,5]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 3]
 [2 3 4]
 [3 4 5]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 7 8]
 [3 0 5]]

Shape:	(2, 3)
Rank:	2
Is Square: False



In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ones_mat_rct = np.ones((3,3))
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Rectangular Matrix: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
zero_mat_rct = np.zeros((3,3))
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Rectangular Matrix: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Task 2

Create a function named mat_operations() that takes in two matrices a input parameters it should:

1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2. Returns the sum of the matrices.
3. Returns the differen of the matrices.
4. Returns the element-wise multiplication of the matrices.
5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than  (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

Addition


In [ ]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [101]:
M = np.array([
   [3,2,5],
   [6,1,9],
   [5,4,2],         
])
A = np.array([
   [1,2,3],
   [6,5,4],
   [7,8,9]
])

E = np.array([
    [2,7,0],
    [2,4,1],
    [9,1,6]
])

In [ ]:
M + E

array([[ 5,  9,  5],
       [ 8,  5, 10],
       [14,  5,  8]])

Subtraction

In [ ]:
A - E

array([[-1, -5,  3],
       [ 4,  1,  3],
       [-2,  7,  3]])

In [ ]:
A - 3

array([[-2, -1,  0],
       [ 3,  2,  1],
       [ 4,  5,  6]])

Element Wise Multiplication

In [ ]:
A * E

array([[ 2, 14,  0],
       [12, 20,  4],
       [63,  8, 54]])

In [ ]:
M * 3

array([[ 9,  6, 15],
       [18,  3, 27],
       [15, 12,  6]])

Element Wise Division

In [ ]:
M / A

array([[3.        , 1.        , 1.66666667],
       [1.        , 0.2       , 2.25      ],
       [0.71428571, 0.5       , 0.22222222]])

References:

[1] Brain4ce Education Institutions Inc.(2021)."How to Implement Matrices in Python using Numphy?.Available: https://www.edureka.co/blog/matrices-in-python/ Accessed on 20-09-2021.

[2] Tutorials Point(2021)."Pyhton - Matrix".Available: https://www.tutorialspoint.com/python_data_structure/python_matrix.htm Accessed on 20-09-2021

[3] Guru99(2021)."Python Matrix: Transpose, Multiplication, NumPy Arrays Examples". Available:https://www.guru99.com/python-matrix.html Accessed on 20-09-2021